#!/bin/bash
cd ~/forspell
rm ./test/popular_gems/*.dict

for var in $(ls ../gem_src/)
do
  cd ~/gem_src/$var
  rm forspell.dict
  ~/forspell/exe/forspell --gen-dictionary .
  cp forspell.dict ~/forspell/test/popular_gems/$var.forspell.dict
done
